# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Beve(object):
    def setupUi(self, Beve):
        Beve.setObjectName("Beve")
        Beve.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Beve)
        self.centralwidget.setObjectName("centralwidget")
        self.mainStartButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainStartButton.setGeometry(QtCore.QRect(340, 470, 75, 23))
        self.mainStartButton.setObjectName("mainStartButton")
        Beve.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Beve)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Beve.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Beve)
        self.statusbar.setObjectName("statusbar")
        Beve.setStatusBar(self.statusbar)

        self.retranslateUi(Beve)
        QtCore.QMetaObject.connectSlotsByName(Beve)

    def retranslateUi(self, Beve):
        _translate = QtCore.QCoreApplication.translate
        Beve.setWindowTitle(_translate("Beve", "MainWindow"))
        self.mainStartButton.setText(_translate("Beve", "Start "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Beve = QtWidgets.QMainWindow()
    ui = Ui_Beve()
    ui.setupUi(Beve)
    Beve.show()
    sys.exit(app.exec_())
